apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      version: {{ .Values.labels.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        env: {{ .Values.labels.env }}
        version: {{ .Values.labels.version }}
    spec:
      containers:
      - name: db-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: db-configmap
        - secretRef:
            name: db-secret