apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: {{ .Values.labels.app | quote }}
    env: {{ .Values.labels.env | quote }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | quote }}