apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: {{ .Values.labels.app | quote }}
    version: {{ .Values.labels.version | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app | quote }}
    version: {{ .Values.labels.version | quote }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}