replicaCount: 1
name: flaskapp
labels:
  app: flask
  env: dev
  version: v1

image:
  repository: karkironisha/ims
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

configmap:
  MYSQL_HOST: db-service.dj-db.svc.cluster.local
  MYSQL_USER: root
  MYSQL_DB: sql5773176

secret:
  MYSQL_PASSWORD: MTIzNDU2Nzg5  # base64 for '123456789'

