apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
data:
  MYSQL_HOST: {{ .Values.configmap.MYSQL_HOST }}
  MYSQL_USER: {{ .Values.configmap.MYSQL_USER }}
  MYSQL_DB: {{ .Values.configmap.MYSQL_DB }}