apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.secret.MYSQL_PASSWORD | quote }}
