apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    version: {{ .Values.labels.version }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.labels.app }}
    version: {{ .Values.labels.version }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
